[instrument_info]
manufacturer='JEOL'
model='840,6300,6400'


[beam.electron.pinout]
scan_enable = [0]

[transforms]
yflip = true
xflip = true
rotate90 = false

[timings]
# Scan Selector board uses TE 1462051-2 Relay
# Switching delay is 20 ms
ext_switch_delay_ms = 20